### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by InfernalAzazel** [Zheng-Changfu/pro-naive-ui#64]
非常好，我也在做 pro，社区终于有类似 antd pro 组件了。

**Comment by InfernalAzazel** [comment]
建议 layout 先弄出来，用用 支持nuxt3 的

**Comment by Zheng-Changfu** [comment]
每天都在开发，最近在开发这个库依赖的表单库

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月28日 09:32 |
| 收件人 | Zheng-Changfu/pro-naive-ui ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [Zheng-Changfu/pro-naive-ui] 催更 (Issue #64) |

建议 layout 先弄出来用用， 支持nuxt3 的

**Comment by InfernalAzazel** [comment]
> 每天都在开发，最近在开发这个库依赖的表单库
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年11月28日 09:32 | | 收件人 | Zheng-Changfu/pro-naive-ui ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [Zheng-Changfu/pro-naive-ui] 催更 (Issue #64) | 建议 layout 先弄出来用用， 支持nuxt3 的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

很棒，我还是先研究我的，后续在转过来，功能完善了，代码尽量简单写，万一要是以后不更了，社区感兴趣的人容易接上维护。
